### ISSUE TITLE
eROSITA flare processing changes the raw data

### ISSUE THREAD

**Issue by jessicapilling** [DavidT3/DAXA#199]
Currently when flaregti is run, it will add the GTI information as an extension in the raw data's fits file. Eventually we want it to produce an external gti file. However the output of flaregti is incompatible with evtool, so will need a work around to achieve this.

**Comment by DavidT3** [comment]
Decided this is fine as the flare GTIs aren't applied until evtool, so the GTIs in the raw data files can be changed and that's fine as they'll only have an effect once written to another file (at least that is what I took away from the docs).
